version: "3"
services:
# 리버스 프록시를 위한 nginx
    proxy:
        image: nginx:latest
        container_name: proxy
        restart: unless-stopped
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf      
            - ./data/proxy':/var/log/nginx/
        environment:
            TZ: "Asia/Seoul"

        ports:
            - 81:80

# pm2 기반으로 돌아가는 nestjs(Express)
# 파일 리로딩 순서 
# docker exec -it npm run build 
# docker exec -it npm run reload all
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: './backend/Dockerfile.dev'
        volumes:
            - ./data/backend/logs:/usr/src/app/logs
            - ./backend/src/:/usr/src/app/src
            # - ./backend/dist/:/usr/src/app/dist
        ports:
            - "3000"
            
# mysql
    db-mysql:
        container_name: db-mysql
        image: mysql:8
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=MYPASSWORD
            - MYSQL_USER=MYPASSWORD
            - MYSQL_PASSWORD=MYPASSWORD
            - TZ=Asia/Seoul
        command:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - 3307:3306
        
        
        
        
        
        